%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(example_types).

-include("example_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('message') ->
  {struct, [{1, i64},
          {2, string}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('message') ->
  {struct, [{1, undefined, i64, 'id', undefined},
          {2, undefined, string, 'text', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

